spawning builder per job

diff --git a/.github/workflows/container-validation-backends.yml b/.github/workflows/container-validation-backends.yml
--- a/.github/workflows/container-validation-backends.yml
+++ b/.github/workflows/container-validation-backends.yml
@@ -55,31 +55,31 @@ jobs:
   #       run: |
   #         echo '${{ toJson(needs) }}' | jq -e 'to_entries | map(.value.result) | all(. as $result | ["success", "skipped"] | any($result == .))'
 
-  create-buildkit-builders:
-    name: Create Build Builders
-    runs-on: builder-cpu-amd-runner
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+  # create-buildkit-builders:
+  #   name: Create Build Builders
+  #   runs-on: builder-cpu-amd-runner
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
 
-    # - name: debuggin
-    #   shell: bash
-    #   run: |
-    #     sleep 3600 
+  #   # - name: debuggin
+  #   #   shell: bash
+  #   #   run: |
+  #   #     sleep 3600 
         
-    - name: Define buildkit builders
-      uses: ./.github/actions/define-buildkit-builders
-      with:
-        builder_name: ${{ env.BUILDER_NAME }}
-        replicas: '1'
-        linux_amd64: 'true'
-        linux_arm64: 'true'
-        linux_amd64_gpu: 'true'
+  #   - name: Define buildkit builders
+  #     uses: ./.github/actions/define-buildkit-builders
+  #     with:
+  #       builder_name: ${{ env.BUILDER_NAME }}
+  #       replicas: '1'
+  #       linux_amd64: 'true'
+  #       linux_arm64: 'true'
+  #       linux_amd64_gpu: 'true'
 
-    - name: Bootstrap buildkit builder
-      shell: bash
-      run: |
-        docker buildx inspect --bootstrap
+  #   - name: Bootstrap buildkit builder
+  #     shell: bash
+  #     run: |
+  #       docker buildx inspect --bootstrap
 
 
   # test-building:
@@ -117,38 +117,38 @@ jobs:
 
 
 
-  cleanup-cluster-builder:
-    name: Cleanup Builder
-    runs-on: builder-cpu-amd-runner
-    # needs: [operator, vllm, sglang, trtllm]
-    needs: [operator]
-    if: always()
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+  # cleanup-cluster-builder:
+  #   name: Cleanup Builder
+  #   runs-on: builder-cpu-amd-runner
+  #   # needs: [operator, vllm, sglang, trtllm]
+  #   needs: [operator]
+  #   if: always()
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
 
-    # - name: debuggin
-    #   shell: bash
-    #   run: |
-    #     sleep 3600 
+  #   # - name: debuggin
+  #   #   shell: bash
+  #   #   run: |
+  #   #     sleep 3600 
         
-    - name: Define buildkit builders
-      uses: ./.github/actions/define-buildkit-builders
-      with:
-        builder_name: ${{ env.BUILDER_NAME }}
-        replicas: '1'
-        linux_amd64: 'true'
-        linux_arm64: 'true'
-        linux_amd64_gpu: 'true'
-    - name: Cleanup Buildkit Builder
-      shell: bash
-      run: |
-        docker buildx rm ${{ env.BUILDER_NAME }} || true
+  #   - name: Define buildkit builders
+  #     uses: ./.github/actions/define-buildkit-builders
+  #     with:
+  #       builder_name: ${{ env.BUILDER_NAME }}
+  #       replicas: '1'
+  #       linux_amd64: 'true'
+  #       linux_arm64: 'true'
+  #       linux_amd64_gpu: 'true'
+  #   - name: Cleanup Buildkit Builder
+  #     shell: bash
+  #     run: |
+  #       docker buildx rm ${{ env.BUILDER_NAME }} || true
 
 
   operator:
     # needs: changed-files
-    needs: [create-buildkit-builders]
+    # needs: [create-buildkit-builders]
     # if: needs.changed-files.outputs.has_code_changes == 'true'
     # strategy:
     #   fail-fast: false
@@ -160,6 +160,7 @@ jobs:
     runs-on: builder-cpu-amd-runner
     env:
       BUILD_PLATFORMS: linux/amd64,linux/arm64
+      JOB_BUILDER_NAME: ${{ env.BUILDER_NAME }}-operator
     steps:
       - name: Output Node Name
         shell: bash
@@ -171,7 +172,7 @@ jobs:
       - name: Define buildkit builders
         uses: ./.github/actions/define-buildkit-builders
         with:
-          builder_name: ${{ env.BUILDER_NAME }}
+          builder_name: ${{ env.JOB_BUILDER_NAME }}
           replicas: '1'
           linux_amd64: 'true'
           linux_arm64: 'true'
@@ -236,6 +237,14 @@ jobs:
       #     aws_push: 'false'
       #     azure_push: 'true'
       #     azure_acr_hostname: ${{ secrets.AZURE_ACR_HOSTNAME }}
+
+      - name: Cleanup Buildkit Builder
+        shell: bash
+        if: always()
+        run: |
+          docker buildx rm ${{ env.JOB_BUILDER_NAME }} || true
+
+
 
   # vllm:
   #   # needs: changed-files
