test full flow

diff --git a/.github/workflows/container-validation-backends.yml b/.github/workflows/container-validation-backends.yml
--- a/.github/workflows/container-validation-backends.yml
+++ b/.github/workflows/container-validation-backends.yml
@@ -55,26 +55,26 @@ jobs:
   #       run: |
   #         echo '${{ toJson(needs) }}' | jq -e 'to_entries | map(.value.result) | all(. as $result | ["success", "skipped"] | any($result == .))'
 
-  # create-buildkit-builders:
-  #   name: Create Build Builders
-  #   runs-on: builder-cpu-amd-runner
-  #   steps:
-  #   - name: Checkout code
-  #     uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+  create-buildkit-builders:
+    name: Create Build Builders
+    runs-on: builder-cpu-amd-runner
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
 
-  #   # - name: debuggin
-  #   #   shell: bash
-  #   #   run: |
-  #   #     sleep 3600 
+    # - name: debuggin
+    #   shell: bash
+    #   run: |
+    #     sleep 3600 
         
-  #   - name: Define buildkit builders
-  #     uses: ./.github/actions/define-buildkit-builders
-  #     with:
-  #       builder_name: ${{ env.BUILDER_NAME }}
-  #       replicas: '1'
-  #       linux_amd64: 'true'
-  #       linux_arm64: 'true'
-  #       linux_amd64_gpu: 'true'
+    - name: Define buildkit builders
+      uses: ./.github/actions/define-buildkit-builders
+      with:
+        builder_name: ${{ env.BUILDER_NAME }}
+        replicas: '1'
+        linux_amd64: 'false'
+        linux_arm64: 'true'
+        linux_amd64_gpu: 'true'
 
   #   - name: Bootstrap buildkit builder
   #     shell: bash
@@ -82,68 +82,35 @@ jobs:
   #       docker buildx inspect --bootstrap
 
 
-  # test-building:
-  #   name: test building
-  #   needs: [create-buildkit-builders]
-  #   runs-on: builder-cpu-amd-runner
-  #   steps:
-  #   - name: Checkout code
-  #     uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+  
 
-  #   - name: Define amd64 builder
-  #     uses: ./.github/actions/buildkit-builder
-  #     with:
-  #       builder_name: ${{ env.BUILDER_NAME }}
-  #       mode: create
-  #       platform: linux/amd64
-  #       replicas: '4'
-  #       nodeselector: 'eks.amazonaws.com/nodegroup=cpu-amd-m5-2xlarge,kubernetes.io/arch=amd64'
-  #       tolerations: 'key=nodepool,value=build-nodes,effect=NoSchedule'
+  cleanup-cluster-builder:
+    name: Cleanup Builder
+    runs-on: builder-cpu-amd-runner
+    needs: [ vllm, sglang, trtllm]
+    # needs: [operator]
+    if: always()
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
 
-  #   - name: Define arm64 builder
-  #     uses: ./.github/actions/buildkit-builder
-  #     with:
-  #       builder_name: ${{ env.BUILDER_NAME }}
-  #       mode: append
-  #       platform: linux/arm64
-  #       replicas: '4'
-  #       nodeselector: 'eks.amazonaws.com/nodegroup=cpu-arm-r8g-4xlarge,kubernetes.io/arch=arm64'
-  #       tolerations: 'key=nodepool,value=build-nodes,effect=NoSchedule'
-
-  #   - name: debuggin
-  #     shell: bash
-  #     run: |
-  #       sleep 3600 
-
-
-
-  # cleanup-cluster-builder:
-  #   name: Cleanup Builder
-  #   runs-on: builder-cpu-amd-runner
-  #   # needs: [operator, vllm, sglang, trtllm]
-  #   needs: [operator]
-  #   if: always()
-  #   steps:
-  #   - name: Checkout code
-  #     uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-
-  #   # - name: debuggin
-  #   #   shell: bash
-  #   #   run: |
-  #   #     sleep 3600 
+    # - name: debuggin
+    #   shell: bash
+    #   run: |
+    #     sleep 3600 
         
-  #   - name: Define buildkit builders
-  #     uses: ./.github/actions/define-buildkit-builders
-  #     with:
-  #       builder_name: ${{ env.BUILDER_NAME }}
-  #       replicas: '1'
-  #       linux_amd64: 'true'
-  #       linux_arm64: 'true'
-  #       linux_amd64_gpu: 'true'
-  #   - name: Cleanup Buildkit Builder
-  #     shell: bash
-  #     run: |
-  #       docker buildx rm ${{ env.BUILDER_NAME }} || true
+    - name: Define buildkit builders
+      uses: ./.github/actions/define-buildkit-builders
+      with:
+        builder_name: ${{ env.BUILDER_NAME }}
+        replicas: '1'
+        linux_amd64: 'false'
+        linux_arm64: 'true'
+        linux_amd64_gpu: 'true'
+    - name: Cleanup Buildkit Builder
+      shell: bash
+      run: |
+        docker buildx rm ${{ env.BUILDER_NAME }} || true
 
 
   # operator:
@@ -256,6 +223,7 @@ jobs:
     #       - { arch: arm64, runner: cpu-arm-r8g-4xlarge }
     name: vllm builder
     runs-on: builder-cpu-amd-runner
+    needs: [create-buildkit-builders]
     steps:
       - name: Output Node Name
         shell: bash
@@ -263,32 +231,14 @@ jobs:
           sleep 36000
       - name: Checkout code
         uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-      # - name: Define buildkit builders
-      #   uses: ./.github/actions/define-buildkit-builders
-      #   with:
-      #     builder_name: ${{ env.BUILDER_NAME }}-vllm
-      #     replicas: '1'
-      #     linux_amd64: 'false'
-      #     linux_arm64: 'true'
-      #     linux_amd64_gpu: 'true'
-      - name: TEMP define remote builder fot desting
-        shell: bash
-        run: |
-            docker buildx create \
-              --name k8s-builder \
-              --driver remote \
-              --platform linux/amd64 \
-              tcp://10-0-43-160.default.pod.cluster.local:1234
-
-            docker buildx create \
-              --append \
-              --name k8s-builder \
-              --driver remote \
-              --platform linux/arm64 \
-              tcp://10.0.13.128.default.pod.cluster.local:1234
-
-            docker buildx use k8s-builder
-            docker buildx inspect --bootstrap
+      - name: Define buildkit builders
+        uses: ./.github/actions/define-buildkit-builders
+        with:
+          builder_name: ${{ env.BUILDER_NAME }}
+          replicas: '1'
+          linux_amd64: 'false'
+          linux_arm64: 'true'
+          linux_amd64_gpu: 'true'
       - name: Docker Login
         uses: ./.github/actions/docker-login
         with:
@@ -339,75 +289,57 @@ jobs:
       #     framework: "vllm"
       #     test_type: "pre_merge"
       #     platform_arch: ${{ matrix.platform.arch }}
-      - name: Cleanup Buildkit Builder
+      # - name: Cleanup Buildkit Builder
+      #   shell: bash
+      #   if: always()
+      #   run: |
+      #     docker buildx rm ${{ env.BUILDER_NAME }}-vllm || true
+
+
+  sglang:
+    name: sglang builder
+    runs-on: builder-cpu-amd-runner
+    needs: [create-buildkit-builders]
+    steps:
+      - name: Output Node Name
         shell: bash
-        if: always()
         run: |
-          docker buildx rm ${{ env.BUILDER_NAME }}-vllm || true
+          echo ${K8S_NODE_NAME}
+      - name: Checkout code
+        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+      - name: Define buildkit builders
+        uses: ./.github/actions/define-buildkit-builders
+        with:
+          builder_name: ${{ env.BUILDER_NAME }}
+          replicas: '1'
+          linux_amd64: 'false'
+          linux_arm64: 'true'
+          linux_amd64_gpu: 'true'
 
-
-  # sglang:
-  #   name: sglang builder
-  #   runs-on: builder-cpu-amd-runner
-  #   steps:
-  #     - name: Output Node Name
-  #       shell: bash
-  #       run: |
-  #         echo ${K8S_NODE_NAME}
-  #     - name: Checkout code
-  #       uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-  #     # - name: Define buildkit builders
-  #     #   uses: ./.github/actions/define-buildkit-builders
-  #     #   with:
-  #     #     builder_name: ${{ env.BUILDER_NAME }}-sglang
-  #     #     replicas: '1'
-  #     #     linux_amd64: 'false'
-  #     #     linux_arm64: 'true'
-  #     #     linux_amd64_gpu: 'true'
-
-  #     - name: TEMP define remote builder fot desting
-  #       shell: bash
-  #       run: |
-  #           docker buildx create \
-  #             --name k8s-builder \
-  #             --driver remote \
-  #             --platform linux/amd64 \
-  #             tcp://10-0-43-160.default.pod.cluster.local:1234
-
-  #           docker buildx create \
-  #             --append \
-  #             --name k8s-builder \
-  #             --driver remote \
-  #             --platform linux/arm64 \
-  #             tcp://10.0.13.128.default.pod.cluster.local:1234
-
-  #           docker buildx use k8s-builder
-  #           docker buildx inspect --bootstrap
-
-  #     - name: Docker Login
-  #       uses: ./.github/actions/docker-login
-  #       with:
-  #         ngc_ci_access_token: ${{ secrets.NGC_CI_ACCESS_TOKEN }}
-  #         aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
-  #         aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
-  #         azure_acr_hostname: ${{ secrets.AZURE_ACR_HOSTNAME }}
-  #         azure_acr_user: ${{ secrets.AZURE_ACR_USER }}
-  #         azure_acr_password: ${{ secrets.AZURE_ACR_PASSWORD }}
-  #     - name: Build Container
-  #       id: build-image
-  #       uses: ./.github/actions/docker-build
-  #       with:
-  #         framework: sglang
-  #         target: runtime
-  #         multi_arch_build: 'true'
-  #         multi_arch_push: 'false'
-  #         push: 'false'
-  #         ci_token: ${{ secrets.CI_TOKEN }}
-  #         aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
-  #         sccache_s3_bucket: ${{ secrets.SCCACHE_S3_BUCKET }}
-  #         aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
-  #         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      - name: Docker Login
+        uses: ./.github/actions/docker-login
+        with:
+          ngc_ci_access_token: ${{ secrets.NGC_CI_ACCESS_TOKEN }}
+          aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
+          azure_acr_hostname: ${{ secrets.AZURE_ACR_HOSTNAME }}
+          azure_acr_user: ${{ secrets.AZURE_ACR_USER }}
+          azure_acr_password: ${{ secrets.AZURE_ACR_PASSWORD }}
+      - name: Build Container
+        id: build-image
+        uses: ./.github/actions/docker-build
+        with:
+          framework: sglang
+          target: runtime
+          multi_arch_build: 'true'
+          multi_arch_push: 'false'
+          push: 'false'
+          ci_token: ${{ secrets.CI_TOKEN }}
+          aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
+          sccache_s3_bucket: ${{ secrets.SCCACHE_S3_BUCKET }}
+          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
+          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   #     # - name: Docker Tag and Push
   #     #   uses: ./.github/actions/docker-tag-push
   #     #   with:
@@ -435,66 +367,49 @@ jobs:
   #         docker buildx rm ${{ env.BUILDER_NAME }}-sglang || true
 
 
-  # trtllm:
-  #   name: trtllm builder
-  #   runs-on: builder-cpu-amd-runner
-  #   steps:
-  #     - name: Output Node Name
-  #       shell: bash
-  #       run: |
-  #         echo ${K8S_NODE_NAME}
-  #     - name: Checkout code
-  #       uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-  #     # - name: Define buildkit builders
-  #     #   uses: ./.github/actions/define-buildkit-builders
-  #     #   with:
-  #     #     builder_name: ${{ env.BUILDER_NAME }}-trtllm
-  #     #     replicas: '1'
-  #     #     linux_amd64: 'false'
-  #     #     linux_arm64: 'true'
-  #     #     linux_amd64_gpu: 'true'
-  #     - name: TEMP define remote builder fot desting
-  #       shell: bash
-  #       run: |
-  #           docker buildx create \
-  #             --name k8s-builder \
-  #             --driver remote \
-  #             --platform linux/amd64 \
-  #             tcp://10-0-43-160.default.pod.cluster.local:1234
-
-  #           docker buildx create \
-  #             --append \
-  #             --name k8s-builder \
-  #             --driver remote \
-  #             --platform linux/arm64 \
-  #             tcp://10.0.13.128.default.pod.cluster.local:1234
-
-  #           docker buildx use k8s-builder
-  #           docker buildx inspect --bootstrap
-  #     - name: Docker Login
-  #       uses: ./.github/actions/docker-login
-  #       with:
-  #         ngc_ci_access_token: ${{ secrets.NGC_CI_ACCESS_TOKEN }}
-  #         aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
-  #         aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
-  #         azure_acr_hostname: ${{ secrets.AZURE_ACR_HOSTNAME }}
-  #         azure_acr_user: ${{ secrets.AZURE_ACR_USER }}
-  #         azure_acr_password: ${{ secrets.AZURE_ACR_PASSWORD }}
-  #     - name: Build Container
-  #       id: build-image
-  #       uses: ./.github/actions/docker-build
-  #       with:
-  #         framework: trtllm
-  #         target: runtime
-  #         multi_arch_build: 'true'
-  #         multi_arch_push: 'false'
-  #         push: 'false'
-  #         ci_token: ${{ secrets.CI_TOKEN }}
-  #         aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
-  #         sccache_s3_bucket: ${{ secrets.SCCACHE_S3_BUCKET }}
-  #         aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
-  #         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  trtllm:
+    name: trtllm builder
+    runs-on: builder-cpu-amd-runner
+    needs: [create-buildkit-builders]
+    steps:
+      - name: Output Node Name
+        shell: bash
+        run: |
+          echo ${K8S_NODE_NAME}
+      - name: Checkout code
+        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+      - name: Define buildkit builders
+        uses: ./.github/actions/define-buildkit-builders
+        with:
+          builder_name: ${{ env.BUILDER_NAME }}
+          replicas: '1'
+          linux_amd64: 'false'
+          linux_arm64: 'true'
+          linux_amd64_gpu: 'true'
+      - name: Docker Login
+        uses: ./.github/actions/docker-login
+        with:
+          ngc_ci_access_token: ${{ secrets.NGC_CI_ACCESS_TOKEN }}
+          aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
+          azure_acr_hostname: ${{ secrets.AZURE_ACR_HOSTNAME }}
+          azure_acr_user: ${{ secrets.AZURE_ACR_USER }}
+          azure_acr_password: ${{ secrets.AZURE_ACR_PASSWORD }}
+      - name: Build Container
+        id: build-image
+        uses: ./.github/actions/docker-build
+        with:
+          framework: trtllm
+          target: runtime
+          multi_arch_build: 'true'
+          multi_arch_push: 'false'
+          push: 'false'
+          ci_token: ${{ secrets.CI_TOKEN }}
+          aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
+          sccache_s3_bucket: ${{ secrets.SCCACHE_S3_BUCKET }}
+          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
+          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   #     # - name: Docker Tag and Push
   #     #   uses: ./.github/actions/docker-tag-push
   #     #   with:
