No cleanning - first run

diff --git a/.github/workflows/container-validation-backends.yml b/.github/workflows/container-validation-backends.yml
--- a/.github/workflows/container-validation-backends.yml
+++ b/.github/workflows/container-validation-backends.yml
@@ -84,33 +84,33 @@ jobs:
 
   
 
-  cleanup-cluster-builder:
-    name: Cleanup Builder
-    runs-on: builder-cpu-amd-runner
-    needs: [ vllm, sglang, trtllm]
-    # needs: [operator]
-    if: always()
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+  # cleanup-cluster-builder:
+  #   name: Cleanup Builder
+  #   runs-on: builder-cpu-amd-runner
+  #   needs: [ vllm, sglang, trtllm]
+  #   # needs: [operator]
+  #   if: always()
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
 
-    # - name: debuggin
-    #   shell: bash
-    #   run: |
-    #     sleep 3600 
+  #   # - name: debuggin
+  #   #   shell: bash
+  #   #   run: |
+  #   #     sleep 3600 
         
-    - name: Define buildkit builders
-      uses: ./.github/actions/define-buildkit-builders
-      with:
-        builder_name: ${{ env.BUILDER_NAME }}
-        replicas: '1'
-        linux_amd64: 'false'
-        linux_arm64: 'true'
-        linux_amd64_gpu: 'true'
-    - name: Cleanup Buildkit Builder
-      shell: bash
-      run: |
-        docker buildx rm ${{ env.BUILDER_NAME }} || true
+  #   - name: Define buildkit builders
+  #     uses: ./.github/actions/define-buildkit-builders
+  #     with:
+  #       builder_name: ${{ env.BUILDER_NAME }}
+  #       replicas: '1'
+  #       linux_amd64: 'false'
+  #       linux_arm64: 'true'
+  #       linux_amd64_gpu: 'true'
+  #   - name: Cleanup Buildkit Builder
+  #     shell: bash
+  #     run: |
+  #       docker buildx rm ${{ env.BUILDER_NAME }} || true
 
 
   # operator:
@@ -221,14 +221,10 @@ jobs:
     #     platform:
     #       - { arch: amd64, runner: gpu-l40-amd64 }
     #       - { arch: arm64, runner: cpu-arm-r8g-4xlarge }
-    name: vllm builder
+    name: vllm builder multi-arch
     runs-on: builder-cpu-amd-runner
     needs: [create-buildkit-builders]
     steps:
-      - name: Output Node Name
-        shell: bash
-        run: |
-          sleep 36000
       - name: Checkout code
         uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
       - name: Define buildkit builders
@@ -297,7 +293,7 @@ jobs:
 
 
   sglang:
-    name: sglang builder
+    name: sglang builder multi-arch
     runs-on: builder-cpu-amd-runner
     needs: [create-buildkit-builders]
     steps:
@@ -368,7 +364,7 @@ jobs:
 
 
   trtllm:
-    name: trtllm builder
+    name: trtllm builder multi-arch
     runs-on: builder-cpu-amd-runner
     needs: [create-buildkit-builders]
     steps:
