Attempting to build

diff --git a/.github/workflows/container-validation-backends.yml b/.github/workflows/container-validation-backends.yml
--- a/.github/workflows/container-validation-backends.yml
+++ b/.github/workflows/container-validation-backends.yml
@@ -86,34 +86,53 @@ jobs:
         replicas: '4'
         nodeselector: 'eks.amazonaws.com/nodegroup=cpu-arm-r8g-4xlarge,kubernetes.io/arch=arm64'
         tolerations: 'key=nodepool,value=build-nodes,effect=NoSchedule'
-    
+
     - name: Bootstrap buildkit builder
       shell: bash
       run: |
         docker buildx inspect --bootstrap
 
 
-  # cleanup-cluster-builder:
-  #   name: Cleanup Builder
-  #   runs-on: cpu-amd-m5-2xlarge
-  #   steps:
-  #   - name: Cleanup builder
-  #     shell: bash
-  #     run: |
-  #       ddocker buildx rm ${{ env.BUILDER_NAME }} || true
+  test-building:
+    name: test building
+    runs-on: builder-cpu-amd-runner
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+
+    - name: debuggin
+      shell: bash
+      run: |
+        sleep 3600 
+
+
+
+  cleanup-cluster-builder:
+    name: Cleanup Builder
+    runs-on: builder-cpu-amd-runner
+    needs: [test-building]
+    if: always()
+    steps:
+    - name: Cleanup Buildkit Builder
+      shell: bash
+      run: |
+        docker buildx rm ${{ env.BUILDER_NAME }} || true
 
 
   # operator:
-  #   needs: changed-files
-  #   if: needs.changed-files.outputs.has_code_changes == 'true'
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       platform:
-  #         - { arch: amd64, runner: cpu-amd-m5-2xlarge }
-  #         - { arch: arm64, runner: cpu-arm-r8g-4xlarge }
-  #   name: operator (${{ matrix.platform.arch }})
-  #   runs-on: ${{ matrix.platform.runner }}
+  #   # needs: changed-files
+  #   needs: [create-buildkit-builders]
+  #   # if: needs.changed-files.outputs.has_code_changes == 'true'
+  #   # strategy:
+  #   #   fail-fast: false
+  #     # matrix:
+  #     #   platform:
+  #     #     - { arch: amd64, runner: cpu-amd-m5-2xlarge }
+  #     #     - { arch: arm64, runner: cpu-arm-r8g-4xlarge }
+  #   name: Building operator (${{ matrix.platform.arch }})
+  #   runs-on: builder-cpu-amd-runner
+  #   env:
+  #     BUILD_PLATFORM: linux/amd64,linux/arm64
   #   steps:
   #     - name: Output Node Name
   #       shell: bash
@@ -121,8 +140,6 @@ jobs:
   #         echo ${K8S_NODE_NAME}
   #     - name: Checkout code
   #       uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-  #     - name: Set up Docker Buildx
-  #       uses: docker/setup-buildx-action@v3
   #     - name: Docker Login
   #       uses: ./.github/actions/docker-login
   #       with:
