wip

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -64,64 +64,6 @@ jobs:
 
 
 
-  st-trtllm-pipeline:
-    needs: [changed-files]
-    uses: ./.github/workflows/flavor-matrix.yml
-    with:
-      framework: trtllm
-      platforms: '["amd64", "arm64"]'
-      cuda_versions: '["12.9"]'
-      stress_test: '["1", "2"]'
-      extra_tags: |
-        ${{ github.ref_name == 'main' && 'main-trtllm' || '' }}
-        ${{ github.ref_name == 'main' && format('main-trtllm-{0}', github.sha) || '' }}
-      no_cache: false
-      builder_name: ${{ needs.changed-files.outputs.builder_name }}
-      run_tests: false
-      copy_to_acr: false
-    secrets: inherit
-
-  st-vllm-pipeline:
-    needs: [changed-files]
-    uses: ./.github/workflows/flavor-matrix.yml
-    with:
-      framework: vllm
-      platforms: '["amd64", "arm64"]'
-      cuda_versions: '["12.9", "13.0"]'
-      extra_tags: |
-        ${{ github.ref_name == 'main' && 'main-vllm' || '' }}
-        ${{ github.ref_name == 'main' && format('main-vllm-{0}', github.sha) || '' }}
-      no_cache: false
-      builder_name: ${{ needs.changed-files.outputs.builder_name }}
-      build_image: true
-      run_tests: false
-      copy_to_acr: false
-      push_image: true
-    secrets: inherit
-
-  # ============================================================================
-  # SGLANG PIPELINE
-  # ============================================================================
-  st-sglang-pipeline:
-    needs: [changed-files]
-    uses: ./.github/workflows/flavor-matrix.yml
-    with:
-      framework: sglang
-      platforms: '["amd64", "arm64"]'
-      cuda_versions: '["12.9", "13.0"]'
-      extra_tags: |
-        ${{ github.ref_name == 'main' && 'main-sglang' || '' }}
-        ${{ github.ref_name == 'main' && format('main-sglang-{0}', github.sha) || '' }}
-      no_cache: false
-      builder_name: ${{ needs.changed-files.outputs.builder_name }}
-      run_tests: false
-      copy_to_acr: false
-    secrets: inherit
-
-
-
-
-
 #   backend-status-check:
 #     runs-on: ubuntu-latest
 #     needs: [changed-files, vllm-pipeline, sglang-pipeline, trtllm-pipeline, operator]  # THIS list determines blocking jobs
@@ -132,105 +74,105 @@ jobs:
 #           echo '${{ toJson(needs) }}' | jq -e 'to_entries | map(.value.result) | all(. as $result | ["success", "skipped"] | any($result == .))'
 
 
-#   # ============================================================================
-#   # Operator
-#   # ============================================================================
+  # ============================================================================
+  # Operator
+  # ============================================================================
 
-#   operator:
-#     needs: changed-files
-#     if: needs.changed-files.outputs.operator == 'true'
-#     name: Operator
-#     runs-on: prod-default-v2
-#     env:
-#       ECR_HOSTNAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
-#     outputs:
-#       operator_default_image_name: ${{ steps.build-and-push-image.outputs.operator_default_image_name }}
-#       operator_default_tag: ${{ steps.build-and-push-image.outputs.operator_default_tag }}
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-#       - name: Initialize Dynamo Builder
-#         uses: ./.github/actions/init-dynamo-builder
-#         with:
-#           builder_name: ${{ needs.changed-files.outputs.builder_name }}
-#           flavor: general
-#           all_arch: 'true'
-#       - name: Docker Login
-#         uses: ./.github/actions/docker-login
-#         with:
-#           aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
-#           aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
-#           azure_acr_hostname: ${{ secrets.AZURE_ACR_HOSTNAME }}
-#           azure_acr_user: ${{ secrets.AZURE_ACR_USER }}
-#           azure_acr_password: ${{ secrets.AZURE_ACR_PASSWORD }}
-#       - name: Linter
-#         shell: bash
-#         working-directory: ./deploy/operator
-#         run: |
-#           docker buildx build --platform linux/amd64,linux/arm64 --target linter --progress=plain --build-arg DOCKER_PROXY=${ECR_HOSTNAME}/dockerhub/ .
-#       - name: Tester
-#         shell: bash
-#         working-directory: ./deploy/operator
-#         run: |
-#           docker buildx build --platform linux/amd64,linux/arm64 --target tester --progress=plain --build-arg DOCKER_PROXY=${ECR_HOSTNAME}/dockerhub/ .
-#       - name: Set up Go
-#         uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
-#         with:
-#           go-version: '1.25'
-#       - name: Check for uncommitted changes #todo: Make sure this doesn't take too much time
-#         shell: bash
-#         working-directory: ./deploy/operator
-#         run: |
-#           make check
-#       - name: Build and push Container
-#         id: build-and-push-image
-#         shell: bash
-#         working-directory: ./deploy/operator
-#         env:
-#           IMAGE_REGISTRY: ai-dynamo
-#           IMAGE_REPOSITORY: dynamo
-#         run: |
-#           DEFAULT_TAG="${{ github.sha }}-dynamo-operator"
-#           ECR_IMAGE_BASE="${ECR_HOSTNAME}/${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}"
-#           ACR_IMAGE_BASE="${{ secrets.AZURE_ACR_HOSTNAME }}/${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}"
-#           NO_CACHE_FLAG=""
-#           IMAGE_URIS=(
-#             "${ECR_IMAGE_BASE}:${DEFAULT_TAG}"
-#             "${ACR_IMAGE_BASE}:${DEFAULT_TAG}"
-#           )
+  operator:
+    needs: changed-files
+    if: needs.changed-files.outputs.operator == 'true'
+    name: Operator
+    runs-on: prod-default-v2
+    env:
+      ECR_HOSTNAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
+    outputs:
+      operator_default_image_name: ${{ steps.build-and-push-image.outputs.operator_default_image_name }}
+      operator_default_tag: ${{ steps.build-and-push-image.outputs.operator_default_tag }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+      - name: Initialize Dynamo Builder
+        uses: ./.github/actions/init-dynamo-builder
+        with:
+          builder_name: ${{ needs.changed-files.outputs.builder_name }}
+          flavor: general
+          all_arch: 'true'
+      - name: Docker Login
+        uses: ./.github/actions/docker-login
+        with:
+          aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
+          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
+          azure_acr_hostname: ${{ secrets.AZURE_ACR_HOSTNAME }}
+          azure_acr_user: ${{ secrets.AZURE_ACR_USER }}
+          azure_acr_password: ${{ secrets.AZURE_ACR_PASSWORD }}
+      - name: Linter
+        shell: bash
+        working-directory: ./deploy/operator
+        run: |
+          docker buildx build --platform linux/amd64,linux/arm64 --target linter --progress=plain --build-arg DOCKER_PROXY=${ECR_HOSTNAME}/dockerhub/ .
+      - name: Tester
+        shell: bash
+        working-directory: ./deploy/operator
+        run: |
+          docker buildx build --platform linux/amd64,linux/arm64 --target tester --progress=plain --build-arg DOCKER_PROXY=${ECR_HOSTNAME}/dockerhub/ .
+      - name: Set up Go
+        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
+        with:
+          go-version: '1.25'
+      - name: Check for uncommitted changes #todo: Make sure this doesn't take too much time
+        shell: bash
+        working-directory: ./deploy/operator
+        run: |
+          make check
+      - name: Build and push Container
+        id: build-and-push-image
+        shell: bash
+        working-directory: ./deploy/operator
+        env:
+          IMAGE_REGISTRY: ai-dynamo
+          IMAGE_REPOSITORY: dynamo
+        run: |
+          DEFAULT_TAG="${{ github.sha }}-dynamo-operator"
+          ECR_IMAGE_BASE="${ECR_HOSTNAME}/${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}"
+          ACR_IMAGE_BASE="${{ secrets.AZURE_ACR_HOSTNAME }}/${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}"
+          NO_CACHE_FLAG=""
+          IMAGE_URIS=(
+            "${ECR_IMAGE_BASE}:${DEFAULT_TAG}"
+            "${ACR_IMAGE_BASE}:${DEFAULT_TAG}"
+          )
 
-#           if [[ "${{ github.ref_name }}" == "main" ]]; then
-#             NO_CACHE_FLAG="--no-cache"
-#             IMAGE_URIS+=(
-#               "${ECR_IMAGE_BASE}:main-dynamo-operator"
-#               "${ECR_IMAGE_BASE}:main-${DEFAULT_TAG}"
-#               "${ACR_IMAGE_BASE}:main-dynamo-operator"
-#               "${ACR_IMAGE_BASE}:main-${DEFAULT_TAG}"
-#             )
-#           fi
+          if [[ "${{ github.ref_name }}" == "main" ]]; then
+            NO_CACHE_FLAG="--no-cache"
+            IMAGE_URIS+=(
+              "${ECR_IMAGE_BASE}:main-dynamo-operator"
+              "${ECR_IMAGE_BASE}:main-${DEFAULT_TAG}"
+              "${ACR_IMAGE_BASE}:main-dynamo-operator"
+              "${ACR_IMAGE_BASE}:main-${DEFAULT_TAG}"
+            )
+          fi
 
-#           echo "operator_default_image_name=${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${DEFAULT_TAG}" >> $GITHUB_OUTPUT
-#           echo "operator_default_tag=${DEFAULT_TAG}" >> $GITHUB_OUTPUT
-#           TAGGING_FLAGS=$(printf -- '-t %s ' "${IMAGE_URIS[@]}")
-#           echo "flags for docker buildx: ${TAGGING_FLAGS}"
+          echo "operator_default_image_name=${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${DEFAULT_TAG}" >> $GITHUB_OUTPUT
+          echo "operator_default_tag=${DEFAULT_TAG}" >> $GITHUB_OUTPUT
+          TAGGING_FLAGS=$(printf -- '-t %s ' "${IMAGE_URIS[@]}")
+          echo "flags for docker buildx: ${TAGGING_FLAGS}"
 
-#           if [[ "${{ github.event.inputs.no_cache_builds }}" == "true" ]]; then
-#             NO_CACHE_FLAG="--no-cache"
-#           fi
-#           docker buildx build --push \
-#               --platform linux/amd64,linux/arm64 \
-#               --build-arg DOCKER_PROXY=${ECR_HOSTNAME}/dockerhub/ \
-#               ${TAGGING_FLAGS} \
-#               ${NO_CACHE_FLAG} -f Dockerfile .
+          if [[ "${{ github.event.inputs.no_cache_builds }}" == "true" ]]; then
+            NO_CACHE_FLAG="--no-cache"
+          fi
+          docker buildx build --push \
+              --platform linux/amd64,linux/arm64 \
+              --build-arg DOCKER_PROXY=${ECR_HOSTNAME}/dockerhub/ \
+              ${TAGGING_FLAGS} \
+              ${NO_CACHE_FLAG} -f Dockerfile .
 
 
-#           echo "### 🐳 Operator Container Images" >> $GITHUB_STEP_SUMMARY
-#           echo "" >> $GITHUB_STEP_SUMMARY
-#           echo "| Image URI |" >> $GITHUB_STEP_SUMMARY
-#           echo "|-----|" >> $GITHUB_STEP_SUMMARY
-#           for image_uri in "${IMAGE_URIS[@]}"; do
-#             echo "| \`${image_uri}\` |" >> $GITHUB_STEP_SUMMARY
-#           done
+          echo "### 🐳 Operator Container Images" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "| Image URI |" >> $GITHUB_STEP_SUMMARY
+          echo "|-----|" >> $GITHUB_STEP_SUMMARY
+          for image_uri in "${IMAGE_URIS[@]}"; do
+            echo "| \`${image_uri}\` |" >> $GITHUB_STEP_SUMMARY
+          done
 
 
 # # ============================================================================
@@ -530,30 +472,31 @@ jobs:
   #         model_name: "Qwen/Qwen3-0.6B"
   #         test_identifier: ${{ env.FRAMEWORK }}_${{ matrix.profile }}_amd64_${{ github.run_id }}_${{ github.run_attempt }}
 
-  # # ============================================================================
-  # # CLEANUP JOBS
-  # # Clean up ephemeral Kubernetes namespace and resources
-  # # ============================================================================
+  # ============================================================================
+  # CLEANUP JOBS
+  # Clean up ephemeral Kubernetes namespace and resources
+  # ============================================================================
 
-  # clean-k8s-builder:
-  #   name: Clean K8s builder if exists
-  #   runs-on: prod-default-small-v2
-  #   if: always()
-  #   needs: [vllm-pipeline, sglang-pipeline, trtllm-pipeline, operator, changed-files]
-  #   steps:
-  #   - name: Checkout repository
-  #     uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-  #   - name: Create K8s builders (skip bootstrap)
-  #     uses: ./.github/actions/bootstrap-buildkit
-  #     continue-on-error: true
-  #     with:
-  #       builder_name: ${{ needs.changed-files.outputs.builder_name }}
-  #       buildkit_worker_addresses: '' # k8s builder
-  #       skip_bootstrap: true
-  #   - name: Builder Cleanup in case of k8s builder
-  #     shell: bash
-  #     run: |
-  #       docker buildx rm ${{ needs.changed-files.outputs.builder_name }} || true
+  clean-k8s-builder:
+    name: Clean K8s builder if exists
+    runs-on: prod-default-small-v2
+    if: always()
+    # needs: [vllm-pipeline, sglang-pipeline, trtllm-pipeline, operator, changed-files]
+    needs: [operator, changed-files]
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+    - name: Create K8s builders (skip bootstrap)
+      uses: ./.github/actions/bootstrap-buildkit
+      continue-on-error: true
+      with:
+        builder_name: ${{ needs.changed-files.outputs.builder_name }}
+        buildkit_worker_addresses: '' # k8s builder
+        skip_bootstrap: true
+    - name: Builder Cleanup in case of k8s builder
+      shell: bash
+      run: |
+        docker buildx rm ${{ needs.changed-files.outputs.builder_name }} || true
 
 
   # cleanup:
