wip
Signed-off-by: rrubin <rrubin@nvidia.com>

diff --git a/.github/workflows/shared-test.yml b/.github/workflows/shared-test.yml
--- a/.github/workflows/shared-test.yml
+++ b/.github/workflows/shared-test.yml
@@ -102,22 +102,26 @@ jobs:
     #       - 9000:9000
           # - 9001:9001
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
-      - name: Run Sanity Check on Runtime Image
+      - name: Hello
         shell: bash
         run: |
-          ls -la 
+          echo "hello"
+      # - name: Checkout repository
+      #   uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
+      # - name: Run Sanity Check on Runtime Image
+      #   shell: bash
+      #   run: |
+      #     ls -la 
 
-          set +e
-          python ./dynamo/deploy/sanity_check.py --runtime-check --no-gpu-check
-          SANITY_CHECK_EXIT_CODE=$?
-          if [ ${SANITY_CHECK_EXIT_CODE} -ne 0 ]; then
-            echo "ERROR: Sanity check failed - ai-dynamo packages not properly installed"
-            exit ${SANITY_CHECK_EXIT_CODE}
-          else
-            echo "✅ Sanity check passed"
-          fi
+      #     set +e
+      #     python ./dynamo/deploy/sanity_check.py --runtime-check --no-gpu-check
+      #     SANITY_CHECK_EXIT_CODE=$?
+      #     if [ ${SANITY_CHECK_EXIT_CODE} -ne 0 ]; then
+      #       echo "ERROR: Sanity check failed - ai-dynamo packages not properly installed"
+      #       exit ${SANITY_CHECK_EXIT_CODE}
+      #     else
+      #       echo "✅ Sanity check passed"
+      #     fi
       # - name: Run CPU-only tests (parallelized)
       #   if: ${{ inputs.run_cpu_only_tests }}
       #   timeout-minutes: ${{ inputs.cpu_only_test_timeout_minutes }}
